### ISSUE TITLE
Add a `tcf.mul` Operation and End-to-end FileCheck Test

### ISSUE THREAD

**Issue by bsarden** [ajarthurs/mlir-npcomp#2]
We should improve the TCFDialect to add a `TCF_MulOp` definition and enhance the lowering paths to be able to lower a `tcf.mul` operation down to the RefBackend. This should match the behavior of [torch.mul](https://pytorch.org/docs/stable/generated/torch.mul.html)

Here's a commit that added a `tcf.max` operation (which is also a BinaryElementWise Operation because we have two operands here. We should be able to follow this commit pretty-closely to implement the desired behavior. 

https://github.com/llvm/mlir-npcomp/commit/c69e9fabc5c3b148722335610fe6844f9bdbe137

Also here's a commit for `tcf.tanh` and `tcf.exp` for reference as well:

https://github.com/llvm/mlir-npcomp/commit/f9b37c55b775d6fec70152db9f08ad7bbe353eff

Another note from Sean, the logic for BypassShapedResults and LowerShapedResultsToMemref has been merged into TCP/Transforms/Bufferize.cpp, and the ShapedResults concept is gone

https://github.com/llvm/mlir-npcomp/blob/14470f9ff6f7de337debe367887a8e70a7dceab7/lib/Dialect/TCP/Transforms/Bufferize.cpp#L1

## Deliverables

* Add a `tcf.mul` variant to [test/npcomp-run-mlir/elementwise.mlir](https://github.com/llvm/mlir-npcomp/blob/f3c75d957b5146b5a53dd2dd53782a0d5b8d6277/test/npcomp-run-mlir/elementwise.mlir#L22)

**Comment by bsarden** [comment]
It's also worth noting that we will want to try and upstream this commit, so there may be some going back / forth on the npcomp side of things once the deliverables are completed :)

**Comment by ajarthurs** [comment]
e5722a2c8f1b5e9713395adba85a47b75107bdf7

**Comment by bsarden** [comment]
Awesome work @ajarthurs! Let's figure out if the Github Actions CI runs for pushes to our forked repo and make sure that the checks all pass before we reach out to Stella / Sean about creating an upstream PR.

**Comment by ajarthurs** [comment]
Merged upstream.
