### ISSUE TITLE
Add a `tcf.conv2d` Operation and lower it to `linalg.conv2d` 

### ISSUE THREAD

**Issue by bsarden** [ajarthurs/mlir-npcomp#3]
As a follow up to #2, we should create a `tcf.conv2d` operation and lower it to `linalg.conv2d`. 

* Note that we should target the Linalg on Tensors Dialect instead of the Linalg On Buffers Dialect, since we lose access to richer `mlir::Type` objects once we lower to `MemRef`'s 
    * A `MemRefType` implies we performed the allocation, so at that point all we have access to is primitive data types (i8, i16, i32, f32). Since we will want to utilize the [QuantDialect](https://github.com/llvm/llvm-project/tree/master/mlir/include/mlir/Dialect/Quant)

## Deliverables

* Create a `conv.mlir` (or something similar) file in [test/npmcomp-run-mlir](https://github.com/llvm/mlir-npcomp/tree/f3c75d957b5146b5a53dd2dd53782a0d5b8d6277/test/npcomp-run-mlir) that verifies that a `tcf.conv2d` operation can be:
    * lowered to the `linalg.conv2d` operation
    * we get the correct convolution result

**Comment by bsarden** [comment]
Here's some notes I found on the Linalg on Tensors dialect:

https://llvm.discourse.group/t/an-update-on-linalg-on-tensors/1878

**Comment by bsarden** [comment]
Notes from our discussion today:

Sounds like `Linalg on Tensors` doesn't have support for `linalg.conv2d` yet:
    * Currently we only have examples of `linalg.conv2d(memref<>, memref<>, ...)` which implies this Linalg on Buffers
    * We can assume that bufferize has already been run for now 

* go from tcf.conv2d -> linalg.conv2d using the Linalg on Buffers Dialect
    * i.e assume `npcomp-opt --tcp-bufferize --tcf-lower-conv2d` so that all function signatures have changed from using `tensor<>` -> `memref<>`
    * "Bufferize" is a synonym for allocating memory

Here's an example in the Linalg tests that use Linalg On Buffers to lower to the named `linalg.conv_2d` Operation

https://github.com/llvm/llvm-project/blob/44865e9169f625b78b7198c0f3f11d9330b01f06/mlir/test/Dialect/Linalg/loops.mlir#L1642-L1646

Here's the list of operations that _should_ work with Linalg on Buffers 
https://mlir.llvm.org/docs/Dialects/Linalg/#operations

## Path to lowering 
```
tcf.conv2d (filler Op with `tensor<>` args)
tcp.conv2d (filler Op with `tensor<>` args)
--- tcp-bufferize pass runs -----
tcp.conv2d (fillerOp with `memref<>` args) i.e. allocate memory
linalg.conv_2d (`Linalg on Buffers` Op using `memref<>` args that can lower to LLVM IR))
```

We can write a FileCheck test that lowers from `tcf.conv2d` -> `linalg.conv_2d` -> LLVM IR and checks the result by chaining together passes with command-line-flags to `npcomp-opt`

https://github.com/llvm/mlir-npcomp/blob/59b7c559f4782be9e1ea5f5e9eb365cf47565426/test/Dialect/TCP/bufferize.mlir#L1

**Comment by bsarden** [comment]
After writing test for the Conv2DNCHWOp, we should try the more generig "linalg.conv" operation.

```
tcf.conv(%input, %filter, %bias, %strides, %padding, %dilation) // tensor<>
tcp.conv(%input, %filter, %bias) {strides = [], padding = [], dilation = [] } // tensor<>
// Bufferize
linalg.conv(%input, %filter, %bias) {strides = [], padding = [], dilation = []} // memref<> 
```

**Comment by bsarden** [comment]
After a few conversations on the mlir-npcomp discord channel, we have finally getting out of "discovery mode" for the first deliverable for this.

The plan is to 

* Create a `tcf.conv2d` that accepts that ATen operands as the operands[0]. The `tcf.conv2d` operation should assert that all the stride / padding / dilation operands are 1 since linalg does not currently support that. 
* Lower the `tcf.conv2d` operation -> `tcp.conv2d` if the operands are valid
* Bufferize the `tcp.conv2d` operation using the exiting TCP-Bufferize pass
* Lower the bufferized `tcp.conv2d` operation to a `linalg.conv_2d_nchw(%input, %filter, %bias)` Operation
* Write FileCheck test(s) that do the following:
    * Verify that we die correctly in `tcf.conv2d` if the stride / padding / dilations are invalid
    * Verify that we can convert with the right arguments a `tcf.conv2d` -> `tcp.conv2d`
    * Verify that we can convert a `tcf.conv2d` -> `linalg.conv_2d_nchw` operation 

[0]: List of ATen Operands for `tcf.conv2d`:
https://github.com/llvm/mlir-npcomp/blob/36d750ca89121db579feeaf07d8046d23620a89f/include/npcomp/Dialect/ATen/IR/GeneratedATenOps.td#L482-L490

**Comment by ajarthurs** [comment]
https://github.com/llvm/mlir-npcomp/pull/137

**Comment by ajarthurs** [comment]
Merged in https://github.com/llvm/mlir-npcomp/commit/85898aaf10ea30237ee1d66c977b966cf7fcf6d0
